<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>NevPlayer.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <PlatformTarget>x64</PlatformTarget>
    <UseRidGraph>true</UseRidGraph>
    <ApplicationIcon>Assets\NevPlayer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\NevPlayer.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\NevPlayer-Symbol.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7175" />
    <PackageReference Include="LibVLCSharp.WinUI" Version="3.10.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NevPlayer.Core\NevPlayer.Core.csproj" />
    <ProjectReference Include="..\NevPlayer.Media\NevPlayer.Media.csproj" />
    <ProjectReference Include="..\NevPlayer.Data\NevPlayer.Data.csproj" />
    <ProjectReference Include="..\NevPlayer.Platform\NevPlayer.Platform.csproj" />
  </ItemGroup>
</Project>
